web:
  build: .
  command: 'bash -c ''node dist/server.js'''
  working_dir: /app/user
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
  volumes:
    - '.:/app/user'
# shell:
#   build: .
#   command: bash
#   working_dir: /app/user
#   environment:
#     PORT: 8080
#   ports:
#     - '8080:8080'
#   volumes:
#     - '.:/app/user'
